### ISSUE TITLE
Document rotation (new branch!)

### ISSUE THREAD

**Issue by dthv** [Kruptein/planarally-docs#35]
With kruptein/PlanarAlly#443, a great new feature has been added: rotation of shapes. This should, of course, be documented. This involves, above all, touching the `select` tool (and the `modes` section, if #34 introduces any).

However, this would, in the current setup, put the documentation ahead of the software's master / stable release branch, which might lead to misunderstandings and unnecessary bug reports. Thus, a new branch containing documentation of upcoming features should be introduced to be merged into master whenever there is a release of the software.

**Comment by Kruptein** [comment]
dev is made

**Comment by dthv** [comment]
Rotation is documented.
