### ISSUE TITLE
Update grid size info

### ISSUE THREAD

**Issue by Kruptein** [Kruptein/planarally-docs#53]
The docs reference this as a DM setting, which since 0.22.0 is no longer the case.

**Comment by dthv** [comment]
Fixed [already in October 2020](https://github.com/Kruptein/planarally-docs/commit/f833d89f997dc0c0eb76d0dd9ca91659f1f443ad#diff-00b695771c2657e8a6feb8d7bea02d1aef587880a9b987ec50d06df2e5bdd9e9) (has it really been so long…?!)
