### ISSUE TITLE
Dm Tools Docs need written

### ISSUE THREAD

**Issue by 10leej** [Kruptein/planarally-docs#8]

**Comment by 10leej** [comment]
@Kruptein Working on this now, though I admit I have no idea there was even a filter tool. Is it actually implemented?

**Comment by Kruptein** [comment]
Yes, it works based on labels applied to shapes

**Comment by 10leej** [comment]
Hmm I guess I haven't ran into it then.

**Comment by Kruptein** [comment]
![image](https://user-images.githubusercontent.com/1814713/79105528-21cbc400-7d71-11ea-9466-b5857f4cfeb1.png)

**Comment by 10leej** [comment]
0.0 Well flew right by my head there, lmao. I'll have to play around with it before I write a doc for it, working on map right now since I would think people want to learn that stuff first.

**Comment by Kruptein** [comment]
Sure, do know that I'm planning on reworking the map tool slightly this release, so that you enter the number of x/y after the selection instead of before.

**Comment by 10leej** [comment]
Yep I'm aware

**Comment by Kruptein** [comment]
Also, it would be a bit easier for others that would like to contribute if you made small PRs instead of something like all the DM tools at once. (I for example don't know whether I can work on some things right now)

**Comment by 10leej** [comment]
Honestly I'm still learning got but I'll do that. Kinda just havent written much of anything so have t really had a reason to even do a pull request.

**Comment by Kruptein** [comment]
That's absolutely fine, I just didn't want to have something happen where you were writing a hole bunch of things and then someone else made a small PR for one specific tool clashing with your docs or such
